# Generated by Django 3.2.4 on 2021-06-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
