# Generated by Django 3.2.4 on 2021-06-04 00:56

import common.validators
from django.db import migrations
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=users.models.image_upload_path, validators=[common.validators.validate_image]),
        ),
    ]
