# Generated by Django 3.2.4 on 2021-06-04 01:00

import common.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.image_upload_path, validators=[common.validators.validate_image]),
        ),
    ]
